### ISSUE TITLE
Poketeams 3.4.0 cause lag/crash and pokemon duplication

### ISSUE THREAD

**Issue by xion87** [TSEcho/PokeTeams#11]
After i upgraded my Poketeams to 3.4.0 some user got their pokemon duplicaed, like a guy catched a pokemon and get spammed with Pokemon send to box (now he got 8 box filled with the same pokemon), i know is caused by poketeams because i see more than one guy on pixelmon channel that reported the same issue and using poketeams... plus it spam a lot of shit on console and cause freeze/crash

**Comment by xion87** [comment]
The error logs:
https://gist.github.com/xion87/1630b593ce287c64048ced22c659d66a
https://gist.github.com/xion87/800f92adfd5ff170f726ddf335c941ed

**Comment by TSEcho** [comment]
Fixed up between updates. Although I’m not sure how anything would’ve duplicated. Those errors basically just stopped the event listener from adding stats. Not much to do with Pokémon

**Comment by xion87** [comment]
maybe it cause huge lag and than cause that
