### ISSUE TITLE
Spam on console

### ISSUE THREAD

**Issue by galoti** [TSEcho/PokeTeams#13]
On server start this happens : https://pastebin.com/giWVx9UA

**Comment by TSEcho** [comment]
One of your placeholders from a different plugin is the same as a placeholder from my plugin which will cause errors. Make sure to find out what that placeholder is and have it removed.

**Comment by TSEcho** [comment]
Will mark this as fixed as this isn't an issue with the plugin. Contact me further on discord if needed
