### ISSUE TITLE
About Tab completion player

### ISSUE THREAD

**Issue by TomGiHub** [TSEcho/PokeTeams#15]
For example, use/teams promote <player> .Use Tab completion player ，Real-time online players will not be completed if the player name is not manually entered and the TAB is completed,but complete all the players on the server.
It's not just this instruction, it's a lot of other instructions.
下面是中文翻译
(Here is the Chinese translation.)
最新版本的4.0.1 比如用/teams promote <player>  然后<player>如果不手动输入玩家名 按TAB补全的话 不会补全实时在线玩家 而是补全你服务器的所有玩家 如果你服务器有几万个玩家注册量 那会全部显示出来 客户端就会卡住！不止是这个指令 还有很多个指令都是这样

**Comment by TSEcho** [comment]
Promoted command uses Sponge's `User` not `Player`. You can promote people that are not online.
